/*
Copyright (c) 2003-2010, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.html or http://ckeditor.com/license
*/

CKEDITOR.addTemplates('default',{
    imagesPath:CKEDITOR.getUrl(CKEDITOR.plugins.getPath('templates')+'templates/images/'),
    templates:[{
        title:'High Speed Internet',
        image:'template1.jpg',
        description:'A title with some text and a table.',
        html:'<h1 class="main"> High Speed Internet + VoIP Home Phone Bundles </h1> <h2 class="main"> <strong>Lorem ipsum dolor sit amet:</strong> consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. </h2> <div class="surftalkBundlesWrapper"> <ul class="surftalkBundles"> <li class="elementWrapper"> <div class="heading"> SURFTALK Local </div> <div class="contentWrapper"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> <div class="centerAllign">+ </div> <p>Lorem ipsum dolor sit amet,</p> <a href="#">&gt;Learn more</a> <a href="#" class="blueBig">$64.99/mo.</a> </div> </li> <li class="elementWrapper"> <div class="heading"> SURFTALK 500 </div> <div class="contentWrapper"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> <div class="centerAllign">+ </div> <p>Lorem ipsum dolor sit amet,</p> <a href="#">&gt;Learn more</a> <a href="#" class="blueBig">$69.99/mo.</a> </div> </li> <li class="elementWrapper marginRightNone"> <div class="heading"> SURFTALK Unlimited </div> <div class="contentWrapper"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> <div class="centerAllign">+ </div> <p>Lorem ipsum dolor sit amet,</p> <a href="#">&gt;Learn more</a> <a href="#" class="blueBig">$74.99/mo.</a> </div> </li> </ul><div class="clr">&nbsp;</div> <div class="surftalkBundlesImage"> <img src="/img/surftalkFeature.jpg" width="208" height="183" alt="" /> </div> <div class="surftalkBundlesFeatures"> <strong>Features:</strong> <ul> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet, consectetur </li> <li>Lorem ipsum dolor sit amet, </li> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li> </ul> <a href="#" class="blueBig">Sign up Now!</a> </div> <div class="clr"></div> </div> <div class="offerWrapper elementWrapper"> <div class="offerHeading"> Sign-up before December 15th, 2010 and receive: </div>  <div class="offerContentWrapper"> <ul class="offer"> <li> <div class="offerContent"> FREE Wireless <br />Modem </div> <div class="offerImage"> <img src="/img/offerModem.jpg" width="155" height="78" alt="" /> </div> </li> <li> <div class="offerContent"> FREE VoIP <br />Adapter </div> <div class="offerImage"> <img src="/img/offerAdapter.jpg" width="155" height="78" alt="" /> </div> </li> <li> <div class="offerContent"> FREE International Calling </div> <div class="offerImage"> <img src="/img/offerInternationalCalling.jpg" width="155" height="78" alt="" /> </div> </li> <li class="marginRightNone"> <div class="offerContent"> 50% OFF Adapter for Wireless VoIP </div> <div class="offerImage"> <img src="/img/offerWireless.jpg" width="155" height="78" alt="" /> </div> </li> </ul> </div> <div class="clr"></div> </div> <a href="#" class="offerTab">&gt;Learn more</a>'
    },{
        title:'Choose Your SurfTalk Bundle',
        image:'template2.jpg',
        description:'A title with some text and a table.',
        html:'<h1 class="main"> Choose Your SurfTalk Bundle </h1> <h2 class="main"> <strong>High Speed Internet + VoIP Phone Service Bundle</strong> </h2> <ul class="bundlePlan"> <li class="elementWrapper"> <div class="heading"> SURFTALK Local - $64.99/mo </div> <div class="clr"></div> <div class="contentWrapper"> <div class="image"> <img src="/img/surftalkLocal.jpg" height="128" width="158" alt="" /> </div> <div class="content"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent euismod 	         						pretium nisl, ac gravida nisl mollis quis.</p><br /> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent euismod        						pretium nisl, ac gravida nisl mollis quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue.</p> </div> <div class="clr"></div> </div> </li> <li class="elementWrapper"> <div class="heading"> SURFTALK 500 - $69.99/mo </div> <div class="clr"></div> <div class="contentWrapper"> <div class="image"> <img src="/img/surftalk500.jpg" height="128" width="158" alt="" /> </div> <div class="content"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent euismod         							pretium nisl, ac gravida nisl mollis quis.</p><br /> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent euismod       							pretium nisl, ac gravida nisl mollis quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. </p> </div> <div class="clr"></div> </div> </li> <li class="elementWrapper"> <div class="heading"> SURFTALK Unlimited - $74.99/mo </div> <div class="clr"></div> <div class="contentWrapper"> <div class="image"> <img src="/img/surftalkUnlimited.jpg" height="128" width="158" alt="" /> </div> <div class="content"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent euismod         							pretium nisl, ac gravida nisl mollis quis.</p><br /> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent euismod       							pretium nisl, ac gravida nisl mollis quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus rutrum sodales congue. </p> </div> <div class="clr"></div> </div> </li> </ul> <a href="#" class="blueBig">Sign up Now!</a>'
    },{
        title:'SURFTALK Bundles Comparison ',
        image:'template3.jpg',
        description:'A title with some text and a table.',
        html:'<h1 class="main"> SURFTALK Bundles Comparison </h1> <h2 class="main"> <strong>Compare Surftalk Prices*</strong> </h2> <table cellpadding="0" cellspacing="0" class="compairBundles"> <tr> <td colspan="2" class="head">CiteNet SURFTALK1</td> <td class="head">Bell Bundle2</td> <td class="head">Rogers Bundle3</td> </tr> <tr> <td width="129">High Speed Internet Home Phone Service</td> <td width="169" class="headWrapper"><strong>$74.99</strong></td> <td width="149">$47.95<br /> $34.95<br /> -$5 (bundle savings)<br /> ------------------------<br /> $77.90 </td> <td width="149">$47.95<br /> $34.95<br /> -$5 (bundle savings)<br /> ------------------------<br /> $77.90 </td> </tr> <tr> <td colspan="4"><p>Do our prices appear the same as that of our competitors?</p> <p><strong>Look at the value you are getting with Pathway.</strong></p><br /> <p><strong>Our competitors have hidden costs and extra charges for features that<br /> we offer for FREE.</strong></p></td> </tr> <tr> <td>International Calling</td> <td class="headWrapper">Included for free every month<br /> ($10 value)</td> <td>$4 plus International rate per min ranging from 5 to 15 cents.</td> <td>$24.95 to 19 countries</td> </tr> <tr> <td>International Calling</td> <td class="headWrapper">Included for free every month<br /> ($10 value)</td> <td>$4 plus International rate per min ranging from 5 to 15 cents.</td> <td>$24.95 to 19 countries</td> </tr> <tr> <td>International Calling</td> <td class="headWrapper">Included for free every month<br /> ($10 value)</td> <td>$4 plus International rate per min ranging from 5 to 15 cents.</td> <td>$24.95 to 19 countries</td> </tr> <tr> <td>International Calling</td> <td class="headWrapper">Included for free every month<br /> ($10 value)</td> <td>$4 plus International rate per min ranging from 5 to 15 cents.</td> <td>$24.95 to 19 countries</td> </tr> <tr> <td colspan="2" class="headWrapper"><strong>Monthly minimum savings with SurfTalk:</strong></td> <td><strong>$50.81</strong></td> <td><strong>$50.81</strong></td> </tr> </table> <br /> <div class="bottomContent"> <p>1Pathway Unlimited Bundle, High Speed Internet with VoIP home phone</p> <p>2Bell Total Performance Internet with Choice Package home phone</p> <p>3Rogers Bundle Express with VoIP home phone</p><br /> <p>*Comparison based on prices advertised online</p> </div>'
    },{
        title:'SURFTALK Bundles',
        image:'template4.jpg',
        description:'A title with some text and a table.',
        html:'<h1 class="main"> SURFTALK Bundles </h1> <h2 class="main"> <strong>Promotion offers and bundle savings</strong> </h2> <div class="promotionWrapper elementWrapper"> <div class="promotionHeadingWrapper"> Sign up &amp; Receive </div> <ul class="promotion"> <li> <div class="promotionContentWrapper"> <div class="image"> <img src="/img/promotionSurftalk.jpg" width="198" height="108" alt="" /> </div> <div class="content"> <strong>Sign up before December 15th, 2010</strong> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet.</p> <p>Lorem ipsum dolor sit amet,</p> </div> <div class="clr"></div> </div> </li> <li> <div class="promotionContentWrapper"> <div class="promotionHeading"> <strong>FREE International Calling</strong>$10 VALUE </div> <div class="image"> <img src="/img/promotionInternationalCalling.jpg" width="198" height="108" alt="" /> </div> <div class="content"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet,</p> <strong>Lorem ipsum dolor sit amet?</strong> <ul> <li> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet, </li> <li> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet, </li> </ul> </div> <div class="clr"></div> </div> </li> <li> <div class="promotionContentWrapper"> <div class="promotionHeading"> <strong>FREE Wireless Modem</strong>$106 VALUE </div> <div class="image"> <img src="/img/promotionWirelessModem.jpg" width="198" height="108" alt="" /> </div> <div class="content"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet,</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet,</p> </div> <div class="clr"></div> </div> </li> <li> <div class="promotionContentWrapper"> <div class="promotionHeading"> <strong>FREE VoIP Phone Adapter</strong>$89 VALUE </div> <div class="image"> <img src="/img/promotionPhoneAdapter.jpg" width="198" height="108" alt="" /> </div> <div class="content"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet,</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet,</p> </div> <div class="clr"></div> </div> </li> </ul> </div>'
    },{
        title:'User Guides and FAQs ',
        image:'template5.jpg',
        description:'A title with some text and a table.',
        html:'<ul> <li><a href="#tabs-1"><span>Customer Support</span></a></li> </ul> <div id="tabs-1"> <h1 class="main"> User Guides and FAQs </h1> <div class="content"> <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus augue elit, auctor non vulputate sed, mollis ut purus. Curabitur sit amet   							enim elit, sit amet faucibus est. Proin quam libero, fringilla sit amet molestie pellentesque, posuere eu elit. </p> <br /> <ul class="bundlePlan"> <li class="elementWrapper"> <div class="heading"> Internet Connection </div> <div class="clr"></div> <div class="contentWrapper"> <div class="customerSupportContent"> <ul class="customerSupport"> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#" class="subList">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#" class="subList">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> </ul> </div> <div class="customerSupportImage"> <img src="/img/customerSupportInternet.jpg" height="128" width="198" alt="" /> </div> <div class="clr"></div> </div> </li> <li class="elementWrapper"> <div class="heading"> Spam and Virus Control </div> <div class="clr"></div> <div class="contentWrapper"> <div class="customerSupportContent"> <ul class="customerSupport"> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> </ul> </div> <div class="customerSupportImage"> <img src="/img/customerSupportVirusControl.jpg" height="128" width="198" alt="" /> </div> <div class="clr"></div> </div> </li> <li class="elementWrapper"> <div class="heading"> Email Help </div> <div class="clr"></div> <div class="contentWrapper"> <div class="customerSupportContent"> <ul class="customerSupport"> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> <li> <a href="#">Lorem ipsum dolor sit amet</a> </li> </ul> </div> <div class="customerSupportImage"> <img src="/img/customerSupportEmailHelp.jpg" height="128" width="198" alt="" /> </div> <div class="clr"></div> </div> </li> </ul> </div> </div>'
    },{
        title:'User Guides and FAQs ',
        image:'template6.jpg',
        description:'A title with some text and a table.',
        html:'<h1 class="main"> Online Support Tools </h1> <div class="content"> <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elementum neque pulvinar ligula eleifend in tristique augue iaculis. Maecenas 							ut purus tellus. Etiam ultrices ligula ornare mauris fermentum sed interdum ante rutrum. </p> <br /> <p> <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong> Proin elementum neque pulvinar ligula eleifend in tristique augue  							iaculis. Maecenas ut purus tellus. Etiam ultrices ligula ornare mauris fermentum sed interdum ante rutrum.Pathway LiveChat is a quick and           					convenient way to contact, and communicate with, our Technical Support Representatives, using a secure live "chat" screen. With LiveChat. </p> <br /> <div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/clickHereIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayContent"> <a href="#">Click here for more info</a> </div> <div class="clr"></div> </div> <br /> <div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/liveChatIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayContent"> <a href="#">Log in to start a LiveChat session</a> </div> <div class="clr"></div> </div> <br /> <p> <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong> Proin elementum neque pulvinar ligula eleifend in tristique augue  							iaculis. Maecenas ut purus tellus. Etiam ultrices ligula ornare mauris fermentum sed interdum ante rutrum.Pathway LiveChat is a quick and           					convenient way to contact, and communicate with, our Technical Support Representatives, using a secure live "chat" screen. With LiveChat. </p> <br /> <div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/clickHereIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayContent"> <a href="#">Click here for more info</a> </div> <div class="clr"></div> </div> </div>'
    },{
        title:'Dial-up Internet Access',
        image:'template7.jpg',
        description:'A title with some text and a table.',
        html:'<ul> <li><a href="#tabs-1"><span>Dial-up Internet</span></a></li> <li><a href="#tabs-2"><span>V2 Accelerated Access</span></a></li> <li><a href="#tabs-3"><span>FAQ</span></a></li> </ul> <div id="tabs-1"> <h1 class="main"> Dial-up Internet Access </h1> <h2 class="main"> Stay connected with family and friends from around the world! Pathways high quality, affordable Internet dial-up service offers a complete range of 					features for your personal or business needs. </h2> <div class="dialUpInternetWrapper"> <ul class="dialUpInternet"> <li class="elementWrapper"> <div class="heading"> Family Dial-up Plans </div> <div class="contentWrapper"> <div class="dialUpInternetImage"> <img src="/img/familyInternetPlan.jpg" width="188" height="128" alt="" /> </div> <br /> <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent                						euismod pretium nisl, ac gravida nisl mollis quis. </p> <br /> <p><strong>Plan 1F</strong> - 250 hours/month</p> <p><strong>Plan 3F</strong> - 500 hours/month</p> <br /> <br /> <a href="#">&gt;Learn more</a> <a href="#" class="blueBig">Sign up Online!</a> </div> </li> <li class="elementWrapper marginRightNone"> <div class="heading"> Single Access Dial-up Plan </div> <div class="contentWrapper"> <div class="dialUpInternetImage"> <img src="/img/singleAccessInternetPlan.jpg" width="188" height="128" alt="" /> </div> <br /> <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus rutrum sodales congue. Nullam sed libero lorem. Praesent                						euismod pretium nisl, ac gravida nisl mollis quis. </p> <br /> <p><strong>Plan 1F</strong> - 250 hours/month</p> <p><strong>Plan 3F</strong> - 500 hours/month</p> <p><strong>Plan 1F</strong> - 250 hours/month</p> <p><strong>Plan 3F</strong> - 500 hours/month</p> <a href="#">&gt;Learn more</a> <a href="#" class="blueBig">Sign up Online!</a> </div> </li> </ul> <h3 class="main"> Existing CiteNet customers upgrade your plan here! </h3> <div class="internetAccess"> <strong>Lorem ipsum dolor sit amet: </strong> <ul> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus  rutrum sodales congue. Lorem ipsum dolor sit amet, consectetur </li> <li>Lorem ipsum dolor sit amet, </li> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li> </ul> </div> <div class="clr"></div> </div> <div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/phoneIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayText"> <p><strong>Do you prefer to sign up by phone or have more questions?</strong></p> <p>Call us at 514-861-5050 (in Montreal) or 1-866-962-4480 (outside Montreal)</p> </div>'
    },{
        title:'Recommended Reading',
        image:'template8.jpg',
        description:'A title with some text and a table.',
        html:'<h1 class="main"> Online Support Tools </h1> <table cellpadding="0" cellspacing="0" class="customerSupport"> <tr> <td width="290" height="90" valign="top" align="left">Dial-up access numbers: </td> <td width="390"> <table> <tr> <td width="230">Montreal</td> <td>514-861-5400</td> </tr> <tr> <td>Baie-St-Paul</td> <td>418-665-7637</td> </tr> <tr> <td>Chicoutimi</td> <td>418-696-2062</td> </tr> <tr> <td>Cornwall</td> <td>613-932-3941</td> </tr>  </table>  </td> </tr> <tr> <td>Email Address: </td> <td>username@citenet.net </td> </tr> <tr> <td>POP3 Account:</td> <td>Your username</td> </tr> <tr> <td>POP3 Server:</td> <td>pop.citenet.net</td> </tr> <tr> <td>SMTP Server:</td> <td>smtp.citenet.net</td> </tr> <tr> <td>News Server:</td> <td>news.citenet.net </td> </tr> <tr> <td>IP Address:</td> <td>Assigned by server</td> </tr> <tr> <td>Primary DNS:</td> <td>205.151.205.151</td> </tr> <tr> <td>Secondary DNS:</td> <td>206.123.38.100</td> </tr> <tr> <td>Domain Name:</td> <td>citenet.net</td> </tr> </table>'
    },{
        title:'Click here for more info',
        image:'template13.jpg',
        description:'A title with some text and a table.',
        html:'<div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/clickHereIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayContent"> <a href="#">Click here for more info</a> </div> <div class="clr"></div> </div>'
    },{
        title:'sign up by phone or have more questions?',
        image:'template12.jpg',
        description:'A title with some text and a table.',
        html:'<div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/phoneIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayText"> <p><strong>Do you prefer to sign up by phone or have more questions?</strong></p> <p>Call us at 514-861-5050 (in Montreal) or 1-866-962-4480 (outside Montreal)</p> </div> <div class="clr"></div> </div>'
    },{
        title:'Log in to start a LiveChat session',
        image:'template14.jpg',
        description:'A title with some text and a table.',
        html:'<div class="grayBox grayWrapper cornerHolder"> <div class="grayIcon"> <img src="/img/liveChatIcon.jpg" width="40" height="40" alt=""/> </div> <div class="grayContent"> <a href="#">Log in to start a LiveChat session</a> </div> <div class="clr"></div> </div>'
    }]
});